name: Deploy Report to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy report folder to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report   
          publish_branch: gh-pages  